### ISSUE TITLE
Wrong cursor-position after new-line (ENTER)

### ISSUE THREAD

**Issue by Lunardis** [buildersbrewery/sublime-lsl#4]
Hello again,

my indention-style is `K & R`, and it works when it comes to autocompletions. But something odd happens when I press the <kbd>ENTER</kbd> for the new line. Instead of being indented with 4 characters it suddenly doesn't indent and is on the same level as the parent.

I thought it is because the indention-styles and changed to others, but it seems not related with this selection.

How can I recover the default behavior again?

### Expected behavior (see cursor)

```lsl
default {
    if(x) { // <- Press ENTER
        |
    }
}
```

### Actual behavior (see cursor)

```lsl
default {
    if(x) { // <- Press ENTER_
    |
    }
}
```

### Steps to reproduce

Press Enter on the position where the comment starts with the // characters in an LSL document.

### Environment

```
=BB= LSL:
    version: 1.4.1
    installed via Package Control: True

Sublime Text:
    channel: stable
    build: 3143
    portable: False
    platform: MacOS Sierra ( 10.12.6 )
    architecture: x64
```

**Comment by buildersbrewery** [comment]
will be fixed in the next release

**Comment by buildersbrewery** [comment]
@Lunardis As a temporary work-around you can manually edit `Packages/=BB= LSL/.sublime/metadata/LSL General.tmPreferences` and adjust settings there accordingly.

![image](https://user-images.githubusercontent.com/13032004/34450306-f424e688-ed05-11e7-9c6d-7ba58ad9563e.png)

**Comment by buildersbrewery** [comment]
## Sneak Preview

> requires `Build 3154+`

![indent_styles](https://user-images.githubusercontent.com/13032004/34655894-ae570e16-f411-11e7-9c99-edbba5a9877e.gif)
