### ISSUE TITLE
Firestorm preprocessor not parsed/linted correctly

### ISSUE THREAD

**Issue by MisterFoxi** [buildersbrewery/sublime-lsl#5]
According the project description, it's my understanding that directive like `#include` or `switch` should be implemented but, for me at least, they appears as error.

```lsl
#define USE_SWITCHES
...

switch (function)
        {
            case RNDGETINT: 
            {   
                data=data+","+(string)lslPRNGRandomInteger(seed);
                break;
            }
            case RNDGETFLOAT: 
            {   
                for (i=0;i<NumDice;i++){

                }
                data=data+","+(string)lslPRNGRandomFloat(seed);
                break;
            }
            case RNDGETKEY: 
            {
                data=data+","+(string)lslPRNGRandomKey(seed);
                break;
            }
            case RNDSETSEED: 
            {   
                seed=llList2Integer(Payload, 1);
                data=data+","+"ok";
                break;
            }

        }
```

gave a syntax error at 'case RNDGETINT: '

Did I missed something in the settings or misunderstood that functionality for the linter ?

Thanks.

### Environment

```text
=BB= LSL:

    version: 1.4.1
    installed via Package Control: True

Sublime Text:

    channel: ?
    build: ?
    portable: ?
    platform: macOS
    architecture: x64
```

**Comment by buildersbrewery** [comment]
SublimeLinter runs lslint with these flags:

* i
* m
* w
* z

Compare:

https://github.com/Makopo/lslint/blob/8c29d5ff36d47395932477a7514b3ca729a0a8f3/lslmini.cc#L855-L883

https://github.com/XenHat/SublimeLinter-contrib-lslint/blob/6674409782a32113e724a1b1e44967bcd5b43989/linter.py#L179-L191

Currently the syntax file at `./.sublime/syntaxes/LSL.sublime-syntax` doesn't support the preprocessor code. However that shouldn't be a problem, as that only gives the visual feedback. I'll fix that in the next release.

Looking at your [firestorm preprocessor](http://wiki.phoenixviewer.com/fs_preprocessor) code, I noticed two things. Keep in mind, I do not use this so here's a guess:

* You are missing a default statement within the switch. Compare the [firestorm preprocessor](http://wiki.phoenixviewer.com/fs_preprocessor) docs.
* The switch parameter compared to the value in one of the statements results in an integer as that is the condition passed to the built `if ... else if ... else` construct. So you might be able call a function there that returns whatever, but I haven't tested that. In your case `function` could be an `integer function` which is then compared to the constants in the built conditional statements as in `if (function == RNDGETINT) { .... }`. I'm also not sure if your `RNDGETINT` is a user declared function in your case, and I'm not sure if the [firestorm preprocessor](http://wiki.phoenixviewer.com/fs_preprocessor) can handle that. But you'd have to test.

**Comment by buildersbrewery** [comment]
As a follow up:

* adding a `default` to the switch, lslint only reports variables as undeclared in your code.
* If the `missing default statement` error was your syntax error, I cannot reproduce your error.

```text
Sublime Text:

    channel: dev
    build: 3156
    portable: True
    platform: Windows
    architecture: x64
```

**Comment by MisterFoxi** [comment]
Hi,
I got the same errors with the example from the firestorm's page: http://wiki.phoenixviewer.com/fs_preprocessor

I'm a bit perplex...

**Comment by buildersbrewery** [comment]
![image](https://user-images.githubusercontent.com/13032004/34645005-410985ec-f343-11e7-844c-0aa7a8ae588f.png)

![image](https://user-images.githubusercontent.com/13032004/34645052-7d10e6ce-f344-11e7-8ef6-0ae2bf9d353c.png)


@MisterFoxi I cannot reproduce your errors with the examples either.

---

Could you try with SublimeLinter `v4.0.0` (or later) as there's a lot of work being done on that currently?

<https://github.com/SublimeLinter/SublimeLinter>

via:

```json
//  in 'Packages/User/Package Control.sublime-settings'

    "install_prereleases":
    [
        "SublimeLinter"
    ]
```

The stable 4.0 release should be out **soonish**, in case you want to wait for that.

**Comment by buildersbrewery** [comment]
@MisterFoxi SublimeLinter v4 and later has an output panel for easier reference.

![screencast](https://user-images.githubusercontent.com/13032004/34645142-eca14d98-f345-11e7-836b-317d83839327.gif)

**Comment by MisterFoxi** [comment]
Still the same...
BB=LSL is v1.4.1
Linter is V4.0.0-rc9
contribution-lslint is v1.4.0
Tooltip is v1.0.3

and I don't have the outputs you seems to have. 

Thanks.

**Comment by buildersbrewery** [comment]
@MisterFoxi Are you sure your issue is related to the `=BB= LSL` package?

Please run `SublimeLinter` in [debug](http://www.sublimelinter.com/en/latest/global_settings.html#debug) mode.

You have redundant packages in your setup. 

Of which `SublimeLinter-contrib-lslint` and `=BB= LSL` both run `lslint` via `SublimeLinter`. To be sure your output for `lslint` is from this package, please check via the debug output to the console (View > Show Console).

---

For the following packages, see their own repo:

* `SublimeLinter-contrib-lslint`: <https://github.com/XenHat/SublimeLinter-contrib-lslint>
* `TooltipLSL`: <https://github.com/makopo/sublime-text-tooltip-lsl>

**Comment by MisterFoxi** [comment]
Ok, a clean install fixed it. 
Thanks for your support.
