### ISSUE TITLE
Opening any LsL script causes error.

### ISSUE THREAD

**Issue by shadoskill** [buildersbrewery/sublime-lsl#6]
### Actual behavior

```text
SublimeLinter: #1 lslint sl_script_d0a7becf2e4425b8834708da06decc0c.lsl
ERROR: ===
Linter crashed.
```

#### Traceback

```text
Traceback (most recent call last):
  File "...\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/backend.py", line 100, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "...\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 758, in lint
    cmd = self.get_cmd()
  File "...\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 482, in get_cmd
    if '@python' in which:
TypeError: argument of type 'property' is not iterable
```

### Steps to reproduce

* This is the first step.
  1. Open a LsL script

### Environment

```text
=BB= LSL:

    version: 2.2.0
    installed via Package Control: True

Sublime Text:

    channel: dev
    build: 3156
    portable: False
    platform: Windows
    architecture: x64
```

**Comment by buildersbrewery** [comment]
@shadoskill This is due to a breaking change within SublimeLinter 4. I'm currently reviewing whether or not the preprocessor linting is possible at all. For now, as a temporary workaround you can force usage of SublimeLinter 3. I know this answer isn't great, sadly my days are limited to 24h as well.

**Comment by buildersbrewery** [comment]
Hello @kaste & @braver,

any pointers how to get this resolved? Compare code:

https://github.com/XenHat/SublimeLinter-contrib-lslint/blob/6674409/linter.py

**Comment by braver** [comment]
We have our documentation here: http://www.sublimelinter.com/en/stable/linter_attributes.html. There are probably a bunch of things that need to happen with that plugin. There has been an extensive beta period with a lot of communication earlier this year, and we did reach out to most plugins about the breaking changes. I guess you kinda missed that window. I'm not sure what you and @ XenHat already tried, or what's unclear... or are you looking for someone to rewrite the plugin for you?

**Comment by buildersbrewery** [comment]
@braver Using v4 we cannot define `which` nor `run`. We use `which` due to shipping binaries with the plugin (for users who don't have them in PATH) and we use `run` to run the linter with a preprocessor.

**Comment by braver** [comment]
> We use which due to shipping binaries with the plugin

Yeah, that's not really something I would recommend doing. SublimeLinter shouldn't be the only way you can run a linter, it's merely a front-end. There's lots of ways to make stuff easier for end users, but you shouldn't ship linter executables with a SublimeLinter plugin. You'll notice every other plugin comes with an explanation on how to install the executable.

> and we use run to run the linter with a preprocessor

Why, what does it do? If it does what I think it does, that won't work. If you take what's in the buffer, transform it via a preprocessor, and then send it to the linter, how do you take that feedback from the linter and relate it to what's in the buffer? Sublime and the linter will both contain different code and SublimeLinter will not be able to reliably present the feedback from the linter to the user. I guess now I understand some of what is going on in `run`, you're transforming the feedback back to the original code's layout?

**Comment by buildersbrewery** [comment]
@braver

* This plug-in defaults to using the binaries in PATH but falls back to using the included binaries when not being able to find any in PATH. This is for beginners who have problems setting up their PATH and to support portable installs on Windows where users don't want to mess with their PATH or simply can't (due to lack of rights).
* See the GIF at [README.md#linting](https://github.com/buildersbrewery/sublime-lsl#linting) for an example how this works or compare XenHat/SublimeLinter-contrib-lslint#6 for the full story.

**Comment by kaste** [comment]
That's just not proper python, @buildersbrewery. None of these methods are actually `@classmethod`s and that's where the original error message comes from `TypeError: argument of type 'property' is not iterable`. You're accessing `executable_path` from the class, not from an instance. `Linter.method` is also not how you invoke methods, you use `self.method`. 

`executable_path` has been deprecated and must be replaced with `lslint` iirc your linter binary name.

**Comment by kaste** [comment]
Other than that the plugin probably works with our deprecation layers. Shipping binaries is totally ok. SublimeLinter doesn't really care.

**Comment by braver** [comment]
> with our deprecation layers

Meaning it will probably break again in the future? ;)

I'm not saying SublimeLinter cares about much of what you're doing here, but this thing seems a bit convoluted compared to the capacity to maintain it all. Yes the platform allows you to override methods, but you then have to be able to keep up with changes that might break your overrides. If you can simplify what you're trying to do here, you'll have an easier time with it.

❤️ @kaste for the actual helpful details. I'm really no help at all here 😉

**Comment by buildersbrewery** [comment]
@kaste Thanks for the input, I believe I fixed everything now.

**Comment by buildersbrewery** [comment]
@XenHat Fix for your code

```diff
--- ./sublimelinter_contrib_lslint.py@c904427
+++ ./sublimelinter_contrib_lslint.py@c904427
@@ -161,7 +161,6 @@
 class Lslint(Linter):
     """Main implementation of the linter interface."""
 
-    syntax = ('lsl', 'ossl')
     executable = 'lslint'
     version_args = '--version'
     version_requirement = '>= 1.0.6'
@@ -170,13 +169,14 @@
     line_col_base = (1, 1)
     tempfile_suffix = 'lsl'
     error_stream = util.STREAM_BOTH
-    selectors = {}
+    defaults = {
+        'selector': 'source.lsl, source.ossl'
+    }
     word_re = None
     inline_settings = None
     inline_overrides = None
     comment_re = None
 
-    @classmethod
     def cmd(self):
         """Override cmd definition/function."""
         # TODO: Add user-configurable setting for these
@@ -188,9 +188,8 @@
         #                               '-u',
         #                               '-w',
         #                               '-z']
-        return [self.executable_path, '-m', '-w', '-z', '-i']
-
-    @classmethod
+        return ['lslint', '-m', '-w', '-z', '-i']
+
     def which(cls, executable):
         """Find native lslint executable."""
 
@@ -201,7 +200,6 @@
             lslint_binary_path = find_linter(lslint_binary_name)
         return lslint_binary_path
 
-    @classmethod
     def run(self, cmd, code):
         """Override the default run command to inject preprocessor step."""
         # print('=== BEGIN LINTER DEBUG ===')
@@ -213,10 +211,10 @@
         #     o_n += 1
 
         mcpp_path = find_mcpp()
-        # if mcpp_path is not None else Linter.communicate(self,cmd,code)
+        # if mcpp_path is not None else self.communicate(cmd,code)
         if mcpp_path is not None:
             opt = '-W0'
-            mcpp_output = Linter.communicate(self, (mcpp_path, opt), code)
+            mcpp_output = self.communicate((mcpp_path, opt), code)
             lines = mcpp_output.splitlines(False)
             line_number = 0
             OutputTuple = namedtuple('OutputTuple', 'mcpp_in_line\
@@ -246,7 +244,7 @@
                         message=message[3]))
                 line_number += 1
             # print("DEBUG:: preproc_bank: {0}".format(preproc_bank[0]))
-            linter_result = Linter.communicate(self, cmd, mcpp_output)
+            linter_result = self.communicate(cmd, mcpp_output)
             # print("DEBUG:: LINTER_OUT output:\n{0}".format(linter_result))
 
             # Go through every error and replace the line number (from the
@@ -307,7 +305,7 @@
 
             print("LINTER:\n"+linter_result)
         else:
-            linter_result = Linter.communicate(self, cmd, code)
+            linter_result = self.communicate(cmd, code)
 
         # print("DEBUG:: Linter output: {0}".format(linter_result))
         # print('=== END LINTER DEBUG ===')
```

**Comment by kaste** [comment]
👍 

Since `cmd` is static, it is better to just define `cmd = ('lslint', '-m', '-w', '-z', '-i')` as a class member. SublimeLinter can apply optimizations for static `cmd`s.

For searching a binary really use `shutil.which`

```python
import shutil

def which(self, executable):
	enhanced_path = os.pathsep.join([
		os.environ.get('PATH', ''), 
		os.path.join(sublime.packages_path(), 'LSL', sublime.platform().strip()),
		os.path.join(sublime.packages_path(), 'LSL', 'bin', 'lslint', sublime.platform().strip()),
		os.path.join(sublime.packages_path(), 'LSL', 'bin', 'mcpp', sublime.platform().strip()),
		# etc ...
	])
	return shutil.which(executable, path=enhanced_path)
```

**Comment by buildersbrewery** [comment]
@kaste for:

```python
def which(self, executable):
    enhanced_path = os.pathsep.join(
        os.environ.get('PATH', ''),
        os.path.join(
            sublime.packages_path(),
            PKG_NAME,
            'bin',
            'lslint',
            sublime.platform() if sublime.platform() in ['linux', 'osx']\
                else 'windows' if platform.release() == 'XP'\
                else 'windows' + platform.architecture()[0][:-3]
        )
    )
    return shutil.which(executable, path=enhanced_path)
```

I receive a `TypeError: which() missing 1 required positional argument: 'executable'`. Looking at:

https://github.com/SublimeLinter/SublimeLinter/blob/f147f974321a227241db62c831958afda74491d5/lint/util.py#L168-L173

switching `executable` with `cmd` in the snippet above doesn't help either.

**Comment by kaste** [comment]
My `which` was an alternative implementation of yours. It goes into the class as a method, then it receives `self` as first arg automatically. 

SublimeLinter will call it once with 'lslint' and you can call it like `self.which('mcpp')` from `run`.

**Comment by kaste** [comment]
Maybe `return shutil.which(executable, path=enhanced_path) or super().which(executable)` for extra compatibility.

**Comment by buildersbrewery** [comment]
SublimeLinter v4 keeps spamming my console with errors. Giving up for today.

**Comment by buildersbrewery** [comment]
@kaste thanks for the valuable feedback. Quick note: You had a small typo as it was `os.pathsep.join([str, str, str])` not `os.pathsep.join(str, str, str)`. Which I fixed in your comment for people who don't read the whole page.

**Comment by buildersbrewery** [comment]
@shadoskill I'll try to push an update later today.

**Comment by buildersbrewery** [comment]
fixed in v4
